name: Build and Test Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci
        npm run postinstall

    - name: Typecheck
      run: npm run typecheck

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    # 移除了测试步骤，因为 package.json 中没有定义测试脚本

    - name: Build/release Electron app
      env:
        GH_TOKEN: ${{ secrets.token }}
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          npm run build:win
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          npm run build:mac
        else
          npm run build:linux
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist_${{ matrix.os }}
        path: dist